In [1]:
# Import dependencies
import pandas as pd
from pathlib import Path

# Name of the CSV file
file = Path('basic_incidents2021.csv')

In [2]:
# Read csv file
df= pd.read_csv(file)
df.head()

,_id,INCIDENT_NUMBER,Initial_CAD_Event_Type,Initial_CAD_Event_Call_Type,Final_Incident_Type,Event_Alarm_Level,Call_Source,Incident_Station_Area,Incident_Ward,Ward_At_Event_Dispatch,Intersection,TFS_Alarm_Time,TFS_Arrival_Time,Last_TFS_Unit_Clear_Time,Persons_Rescued,geometry
0,1,F21133379,FASS - Alarm Single Source,Emergency Fire,31 - Alarm Equipment - Malfunction,0,01 - 911,234.0,24,NaN,Overture Rd / Pilot St,2021-12-14T17:34:10,NaN,2021-12-14T17:43:21,0.0,"{'type': 'Point', 'coordinates': (-79.1989, 43..."
1,2,F21024771,CC - Check Call,Other Emergency Events,59 - Other Public Hazard,0,01 - 911,214.0,25,NaN,Morrish Rd / Willowlea Dr,2021-03-19T23:40:42,2021-03-19T23:47:46,2021-03-19T23:56:16,0.0,"{'type': 'Point', 'coordinates': (-79.1763, 43..."
2,3,F21132262,CCNE - Check Call - Non Emergency,Non Emergency,59 - Other Public Hazard,0,01 - 911,131.0,15,NaN,Rochester Ave / St Ives Cres,2021-12-11T22:58:23,2021-12-11T23:06:03,NaN,0.0,"{'type': 'Point', 'coordinates': (-79.3899, 43..."
3,4,F21040093,VEPI - Vehicle - Personal Injury,Vehicle Incident,62 - Vehicle Collision,0,03 - From Ambulance,415.0,1,NaN,Rexdale Blvd / Highway 27 S,2021-04-30T12:58:26,2021-04-30T13:06:57,2021-04-30T13:23:58,0.0,"{'type': 'Point', 'coordinates': (-79.5958, 43..."
4,5,F21004206,Medical,Medical,Medical,0,03 - From Ambulance,135.0,12,NaN,M5P,2021-01-14T15:49:37,2021-01-14T15:54:47,2021-01-14T16:05:35,0.0,"{'type': 'Point', 'coordinates': (0.0, 0.0)}"

In [3]:
# drop rows without coridnates( long and latitude not given)
newdf = df[df['geometry'] != "{'type': 'Point', 'coordinates': (0.0, 0.0)}"]
newdf.head(2)

,_id,INCIDENT_NUMBER,Initial_CAD_Event_Type,Initial_CAD_Event_Call_Type,Final_Incident_Type,Event_Alarm_Level,Call_Source,Incident_Station_Area,Incident_Ward,Ward_At_Event_Dispatch,Intersection,TFS_Alarm_Time,TFS_Arrival_Time,Last_TFS_Unit_Clear_Time,Persons_Rescued,geometry
0,1,F21133379,FASS - Alarm Single Source,Emergency Fire,31 - Alarm Equipment - Malfunction,0,01 - 911,234.0,24,NaN,Overture Rd / Pilot St,2021-12-14T17:34:10,NaN,2021-12-14T17:43:21,0.0,"{'type': 'Point', 'coordinates': (-79.1989, 43..."
1,2,F21024771,CC - Check Call,Other Emergency Events,59 - Other Public Hazard,0,01 - 911,214.0,25,NaN,Morrish Rd / Willowlea Dr,2021-03-19T23:40:42,2021-03-19T23:47:46,2021-03-19T23:56:16,0.0,"{'type': 'Point', 'coordinates': (-79.1763, 43..."

In [5]:
# remove other characters except coordinates
newdf2 = newdf.replace({'geometry' : "{'type': 'Point', 'coordinates':"}, {'geometry' : ""}, regex = True).replace({'geometry' : "}"}, {'geometry' : ""}, regex = True)
newdf2['geometry'] = newdf2['geometry'].str.replace('(', '')
newdf2['geometry'] = newdf2['geometry'].str.replace(')', '')

C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\1918141312.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  newdf2['geometry'] = newdf2['geometry'].str.replace('(', '')
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\1918141312.py:4: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  newdf2['geometry'] = newdf2['geometry'].str.replace(')', '')

In [6]:
# drop unwanted column
df3 = newdf2.drop(["Ward_At_Event_Dispatch"], axis = 1)

In [7]:
# Split columns with ID and description
df3[["Final_Incident_ID", "Final_Incident_Types"]] = df3['Final_Incident_Type'].str.split('-', 1, expand = True)

df3[["Call_ID", "Call_Origin"]] = df3['Call_Source'].str.split('-', 1, expand = True)

df3[["Location", "Location2"]] = df3['Intersection'].str.split('/', 1, expand = True)

df3.head(2)

C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\2868869549.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df3[["Final_Incident_ID", "Final_Incident_Types"]] = df3['Final_Incident_Type'].str.split('-', 1, expand = True)
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\2868869549.py:4: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df3[["Call_ID", "Call_Origin"]] = df3['Call_Source'].str.split('-', 1, expand = True)
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\2868869549.py:6: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df3[["Location", "Location2"]] = df3['Intersection'].str.split('/', 1, expand = True)

,_id,INCIDENT_NUMBER,Initial_CAD_Event_Type,Initial_CAD_Event_Call_Type,Final_Incident_Type,Event_Alarm_Level,Call_Source,Incident_Station_Area,Incident_Ward,Intersection,...,TFS_Arrival_Time,Last_TFS_Unit_Clear_Time,Persons_Rescued,geometry,Final_Incident_ID,Final_Incident_Types,Call_ID,Call_Origin,Location,Location2
0,1,F21133379,FASS - Alarm Single Source,Emergency Fire,31 - Alarm Equipment - Malfunction,0,01 - 911,234.0,24,Overture Rd / Pilot St,...,NaN,2021-12-14T17:43:21,0.0,"-79.1989, 43.7601",31,Alarm Equipment - Malfunction,01,911,Overture Rd,Pilot St
1,2,F21024771,CC - Check Call,Other Emergency Events,59 - Other Public Hazard,0,01 - 911,214.0,25,Morrish Rd / Willowlea Dr,...,2021-03-19T23:47:46,2021-03-19T23:56:16,0.0,"-79.1763, 43.7971",59,Other Public Hazard,01,911,Morrish Rd,Willowlea Dr

In [8]:
# List all the column names
df3.columns

Index(['_id', 'INCIDENT_NUMBER', 'Initial_CAD_Event_Type',
       'Initial_CAD_Event_Call_Type', 'Final_Incident_Type',
       'Event_Alarm_Level', 'Call_Source', 'Incident_Station_Area',
       'Incident_Ward', 'Intersection', 'TFS_Alarm_Time', 'TFS_Arrival_Time',
       'Last_TFS_Unit_Clear_Time', 'Persons_Rescued', 'geometry',
       'Final_Incident_ID', 'Final_Incident_Types', 'Call_ID', 'Call_Origin',
       'Location', 'Location2'],
      dtype='object')

In [10]:
# Rearrange the columns for new data frame
df_fire = df3[['_id', 'INCIDENT_NUMBER', 'Initial_CAD_Event_Type',
       'Initial_CAD_Event_Call_Type', 'Final_Incident_ID', 'Final_Incident_Types',
       'Event_Alarm_Level', 'Call_ID', 'Call_Origin','Incident_Station_Area',
       'Incident_Ward', 'Location', 'TFS_Alarm_Time', 'TFS_Arrival_Time',
       'Last_TFS_Unit_Clear_Time', 'Persons_Rescued', 'geometry']]
       
df_fire.head(2)

,_id,INCIDENT_NUMBER,Initial_CAD_Event_Type,Initial_CAD_Event_Call_Type,Final_Incident_ID,Final_Incident_Types,Event_Alarm_Level,Call_ID,Call_Origin,Incident_Station_Area,Incident_Ward,Location,TFS_Alarm_Time,TFS_Arrival_Time,Last_TFS_Unit_Clear_Time,Persons_Rescued,geometry
0,1,F21133379,FASS - Alarm Single Source,Emergency Fire,31,Alarm Equipment - Malfunction,0,01,911,234.0,24,Overture Rd,2021-12-14T17:34:10,NaN,2021-12-14T17:43:21,0.0,"-79.1989, 43.7601"
1,2,F21024771,CC - Check Call,Other Emergency Events,59,Other Public Hazard,0,01,911,214.0,25,Morrish Rd,2021-03-19T23:40:42,2021-03-19T23:47:46,2021-03-19T23:56:16,0.0,"-79.1763, 43.7971"

In [11]:
# drop rows with empty values
df_fire2= df_fire.dropna(axis = 0)

In [12]:
# change format of columns with date/time
from datetime import datetime
df_fire2["TFS_Alarm_Time"] = pd.to_datetime(df_fire2["TFS_Alarm_Time"])
df_fire2["TFS_Arrival_Time"] = pd.to_datetime(df_fire2["TFS_Arrival_Time"])
df_fire2["Last_TFS_Unit_Clear_Time"] = pd.to_datetime(df_fire2["Last_TFS_Unit_Clear_Time"])

C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\661493930.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fire2["TFS_Alarm_Time"] = pd.to_datetime(df_fire2["TFS_Alarm_Time"])
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\661493930.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fire2["TFS_Arrival_Time"] = pd.to_datetime(df_fire2["TFS_Arrival_Time"])
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\661493930.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fire2["Last_TFS_Unit_Clear_Time"] = pd.to_datetime(df_fire2["Last_TFS_Unit_Clear_Time"])

In [13]:
# find the time taken and time at scene
df_fire2["Time_Taken_to_Arrive"] = df_fire2["TFS_Arrival_Time"] - df_fire2["TFS_Alarm_Time"]
df_fire2["Total_Time_at_Scene"]= df_fire2["Last_TFS_Unit_Clear_Time"] - df_fire2["TFS_Arrival_Time"]

C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\3651134677.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fire2["Time_Taken_to_Arrive"] = df_fire2["TFS_Arrival_Time"] - df_fire2["TFS_Alarm_Time"]
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\3651134677.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fire2["Total_Time_at_Scene"]= df_fire2["Last_TFS_Unit_Clear_Time"] - df_fire2["TFS_Arrival_Time"]

In [14]:
# convert total time in minutes
df_fire2["Time_Taken_to_Arrive"] = df_fire2["Time_Taken_to_Arrive"].dt.seconds/60
df_fire2["Total_Time_at_Scene"] = df_fire2["Total_Time_at_Scene"].dt.seconds/60

C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\186192938.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fire2["Time_Taken_to_Arrive"] = df_fire2["Time_Taken_to_Arrive"].dt.seconds/60
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\186192938.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_fire2["Total_Time_at_Scene"] = df_fire2["Total_Time_at_Scene"].dt.seconds/60

In [15]:
# check info 
df_fire2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53166 entries, 1 to 134537
Data columns (total 19 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   _id                          53166 non-null  int64
 1   INCIDENT_NUMBER              53166 non-null  object
 2   Initial_CAD_Event_Type       53166 non-null  object
 3   Initial_CAD_Event_Call_Type  53166 non-null  object
 4   Final_Incident_ID            53166 non-null  object
 5   Final_Incident_Types         53166 non-null  object
 6   Event_Alarm_Level            53166 non-null  int64
 7   Call_ID                      53166 non-null  object
 8   Call_Origin                  53166 non-null  object
 9   Incident_Station_Area        53166 non-null  float64
 10  Incident_Ward                53166 non-null  int64
 11  Location                     53166 non-null  object
 12  TFS_Alarm_Time               53166 non-null  datetime64[ns]
 13  TFS_Arrival_Time             53166 non-null  datetime64[ns]
 14  Last_TFS_Unit_Clear_Time     53166 non-null  datetime64[ns]
 15  Persons_Rescued              53166 non-null  float64
 16  geometry                     53166 non-null  object
 17  Time_Taken_to_Arrive         53166 non-null  float64
 18  Total_Time_at_Scene          53166 non-null  float64
dtypes: datetime64[ns](3), float64(4), int64(3), object(9)
memory usage: 8.1+ MB

In [16]:
df_fire2.head()

,_id,INCIDENT_NUMBER,Initial_CAD_Event_Type,Initial_CAD_Event_Call_Type,Final_Incident_ID,Final_Incident_Types,Event_Alarm_Level,Call_ID,Call_Origin,Incident_Station_Area,Incident_Ward,Location,TFS_Alarm_Time,TFS_Arrival_Time,Last_TFS_Unit_Clear_Time,Persons_Rescued,geometry,Time_Taken_to_Arrive,Total_Time_at_Scene
1,2,F21024771,CC - Check Call,Other Emergency Events,59,Other Public Hazard,0,01,911,214.0,25,Morrish Rd,2021-03-19 23:40:42,2021-03-19 23:47:46,2021-03-19 23:56:16,0.0,"-79.1763, 43.7971",7.066667,8.500000
3,4,F21040093,VEPI - Vehicle - Personal Injury,Vehicle Incident,62,Vehicle Collision,0,03,From Ambulance,415.0,1,Rexdale Blvd,2021-04-30 12:58:26,2021-04-30 13:06:57,2021-04-30 13:23:58,0.0,"-79.5958, 43.7173",8.516667,17.016667
5,6,F21084623,WDH - Wires Down - Hydro,Other Emergency Events,50,"Power Lines Down, Arcing",0,04,From Police Services,445.0,2,Puckeridge Cres,2021-08-19 12:08:03,2021-08-19 12:15:08,2021-08-19 12:18:20,0.0,"-79.5631, 43.6643",7.083333,3.200000
8,9,F21137892,FAHR - Alarm Highrise Residential,Emergency Fire,33,"Human - Malicious intent, prank",0,05,Telephone from Monitoring Agency,232.0,21,Lawrence Ave E,2021-12-25 15:04:27,2021-12-25 15:09:35,2021-12-25 15:43:50,0.0,"-79.26810000000002, 43.7506",5.133333,34.250000
10,11,F21079450,FASS - Alarm Single Source,Emergency Fire,32,Alarm System Equipment - Accidental activatio...,0,05,Telephone from Monitoring Agency,332.0,10,John St,2021-08-07 03:59:29,2021-08-07 04:06:58,2021-08-07 04:58:39,0.0,"-79.38950000000001, 43.6459",7.483333,51.683333

In [17]:
# rearrange columns in the final data frame
df_final1 = df_fire2[['_id', 'INCIDENT_NUMBER', 'Initial_CAD_Event_Type',
       'Initial_CAD_Event_Call_Type', 'Final_Incident_ID', 'Final_Incident_Types',
       'Event_Alarm_Level', 'Call_ID', 'Call_Origin','Incident_Station_Area',
       'Incident_Ward', 'Location', 'TFS_Alarm_Time', 'TFS_Arrival_Time', 'Time_Taken_to_Arrive', 
       'Last_TFS_Unit_Clear_Time', 'Total_Time_at_Scene', 'Persons_Rescued', 'geometry']]

df_final1.head(3)

,_id,INCIDENT_NUMBER,Initial_CAD_Event_Type,Initial_CAD_Event_Call_Type,Final_Incident_ID,Final_Incident_Types,Event_Alarm_Level,Call_ID,Call_Origin,Incident_Station_Area,Incident_Ward,Location,TFS_Alarm_Time,TFS_Arrival_Time,Time_Taken_to_Arrive,Last_TFS_Unit_Clear_Time,Total_Time_at_Scene,Persons_Rescued,geometry
1,2,F21024771,CC - Check Call,Other Emergency Events,59,Other Public Hazard,0,01,911,214.0,25,Morrish Rd,2021-03-19 23:40:42,2021-03-19 23:47:46,7.066667,2021-03-19 23:56:16,8.500000,0.0,"-79.1763, 43.7971"
3,4,F21040093,VEPI - Vehicle - Personal Injury,Vehicle Incident,62,Vehicle Collision,0,03,From Ambulance,415.0,1,Rexdale Blvd,2021-04-30 12:58:26,2021-04-30 13:06:57,8.516667,2021-04-30 13:23:58,17.016667,0.0,"-79.5958, 43.7173"
5,6,F21084623,WDH - Wires Down - Hydro,Other Emergency Events,50,"Power Lines Down, Arcing",0,04,From Police Services,445.0,2,Puckeridge Cres,2021-08-19 12:08:03,2021-08-19 12:15:08,7.083333,2021-08-19 12:18:20,3.200000,0.0,"-79.5631, 43.6643"

In [18]:
# Split longitude and latitude into separate columns
df_final1[["Longitude", "Latitude"]] = df_fire2['geometry'].str.split(',', 1, expand = True)

C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\2730398607.py:2: FutureWarning: In a future version of pandas all arguments of StringMethods.split except for the argument 'pat' will be keyword-only.
  df_final1[["Longitude", "Latitude"]] = df_fire2['geometry'].str.split(',', 1, expand = True)
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\2730398607.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final1[["Longitude", "Latitude"]] = df_fire2['geometry'].str.split(',', 1, expand = True)
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\2730398607.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final1[["Longitude", "Latitude"]] = df_fire2['geometry'].str.split(',', 1, expand = True)

In [19]:
# change data type for longitude and latitude 
df_final1["Latitude"] = df_final1["Latitude"].astype(float)
df_final1["Longitude"] = df_final1["Longitude"].astype(float)

C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\3277338801.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final1["Latitude"] = df_final1["Latitude"].astype(float)
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\3277338801.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final1["Longitude"] = df_final1["Longitude"].astype(float)

In [20]:
df_final =df_final1[['_id', 'INCIDENT_NUMBER', 'Initial_CAD_Event_Type',
       'Initial_CAD_Event_Call_Type', 'Final_Incident_ID', 'Final_Incident_Types',
       'Event_Alarm_Level', 'Call_ID', 'Call_Origin','Incident_Station_Area',
       'Incident_Ward', 'Location', 'TFS_Alarm_Time', 'TFS_Arrival_Time', 'Time_Taken_to_Arrive', 
       'Last_TFS_Unit_Clear_Time', 'Total_Time_at_Scene', 'Persons_Rescued', 'Latitude', 'Longitude']]

df_final.head(3)

,_id,INCIDENT_NUMBER,Initial_CAD_Event_Type,Initial_CAD_Event_Call_Type,Final_Incident_ID,Final_Incident_Types,Event_Alarm_Level,Call_ID,Call_Origin,Incident_Station_Area,Incident_Ward,Location,TFS_Alarm_Time,TFS_Arrival_Time,Time_Taken_to_Arrive,Last_TFS_Unit_Clear_Time,Total_Time_at_Scene,Persons_Rescued,Latitude,Longitude
1,2,F21024771,CC - Check Call,Other Emergency Events,59,Other Public Hazard,0,01,911,214.0,25,Morrish Rd,2021-03-19 23:40:42,2021-03-19 23:47:46,7.066667,2021-03-19 23:56:16,8.500000,0.0,43.7971,-79.1763
3,4,F21040093,VEPI - Vehicle - Personal Injury,Vehicle Incident,62,Vehicle Collision,0,03,From Ambulance,415.0,1,Rexdale Blvd,2021-04-30 12:58:26,2021-04-30 13:06:57,8.516667,2021-04-30 13:23:58,17.016667,0.0,43.7173,-79.5958
5,6,F21084623,WDH - Wires Down - Hydro,Other Emergency Events,50,"Power Lines Down, Arcing",0,04,From Police Services,445.0,2,Puckeridge Cres,2021-08-19 12:08:03,2021-08-19 12:15:08,7.083333,2021-08-19 12:18:20,3.200000,0.0,43.6643,-79.5631

In [21]:
# change data type for other columns
df_final["_id"] = df_final["_id"].astype(int)
df_final1["Latitude"] = df_final1["Latitude"].astype(float)
df_final["Time_Taken_to_Arrive"]= df_final['Time_Taken_to_Arrive'].astype(str)
df_final["Total_Time_at_Scene"]= df_final['Total_Time_at_Scene'].astype(str)

df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53166 entries, 1 to 134537
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   _id                          53166 non-null  int32
 1   INCIDENT_NUMBER              53166 non-null  object
 2   Initial_CAD_Event_Type       53166 non-null  object
 3   Initial_CAD_Event_Call_Type  53166 non-null  object
 4   Final_Incident_ID            53166 non-null  object
 5   Final_Incident_Types         53166 non-null  object
 6   Event_Alarm_Level            53166 non-null  int64
 7   Call_ID                      53166 non-null  object
 8   Call_Origin                  53166 non-null  object
 9   Incident_Station_Area        53166 non-null  float64
 10  Incident_Ward                53166 non-null  int64
 11  Location                     53166 non-null  object
 12  TFS_Alarm_Time               53166 non-null  datetime64[ns]
 13  TFS_Arrival_Time             53166 non-null  datetime64[ns]
 14  Time_Taken_to_Arrive         53166 non-null  object
 15  Last_TFS_Unit_Clear_Time     53166 non-null  datetime64[ns]
 16  Total_Time_at_Scene          53166 non-null  object
 17  Persons_Rescued              53166 non-null  float64
 18  Latitude                     53166 non-null  float64
 19  Longitude                    53166 non-null  float64
dtypes: datetime64[ns](3), float64(4), int32(1), int64(2), object(10)
memory usage: 8.3+ MB

C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\4070161930.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["_id"] = df_final["_id"].astype(int)
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\4070161930.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final1["Latitude"] = df_final1["Latitude"].astype(float)
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\4070161930.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["Time_Taken_to_Arrive"]= df_final['Time_Taken_to_Arrive'].astype(str)
C:\Users\gklo4\AppData\Local\Temp\ipykernel_15288\4070161930.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final["Total_Time_at_Scene"]= df_final['Total_Time_at_Scene'].astype(str)

In [22]:
# extract month from the date
df_final["Month"] = pd.to_datetime(df_final["TFS_Alarm_Time"]).dt.strftime('%m')
df_final["Month"]= df_final["Month"].astype(int)

In [23]:
df_finally = df_final.replace({"Total_Time_at_Scene": "0 days 00:"}, {'Total_Time_at_Scene' : ""}, regex = True)
df_finally1 = df_finally.replace({"Total_Time_at_Scene": ":"}, {'Total_Time_at_Scene' : "."}, regex = True)

df_finally2 = df_finally1.replace({"Time_Taken_to_Arrive": "0 days 00:"}, {'Time_Taken_to_Arrive' : ""}, regex = True)

df_finally3 = df_finally2.replace({"Time_Taken_to_Arrive": ":"}, {'Time_Taken_to_Arrive' : "."}, regex = True)
# df_final2 = df_final1.replace({"Time_Taken_to_Arrive": "0 days 00:"}, {'Time_Taken_to_Arrive' : ""}, regex = True)

In [24]:
# change data type in new data columns
df_finally3["Time_Taken_to_Arrive"]= round(df_finally3["Time_Taken_to_Arrive"].astype(float, 3))
df_finally3["Total_Time_at_Scene"]= round(df_finally3["Total_Time_at_Scene"].astype(float, 3))
df_finally3.head(3)

,_id,INCIDENT_NUMBER,Initial_CAD_Event_Type,Initial_CAD_Event_Call_Type,Final_Incident_ID,Final_Incident_Types,Event_Alarm_Level,Call_ID,Call_Origin,Incident_Station_Area,...,Location,TFS_Alarm_Time,TFS_Arrival_Time,Time_Taken_to_Arrive,Last_TFS_Unit_Clear_Time,Total_Time_at_Scene,Persons_Rescued,Latitude,Longitude,Month
1,2,F21024771,CC - Check Call,Other Emergency Events,59,Other Public Hazard,0,01,911,214.0,...,Morrish Rd,2021-03-19 23:40:42,2021-03-19 23:47:46,7.0,2021-03-19 23:56:16,8.0,0.0,43.7971,-79.1763,3
3,4,F21040093,VEPI - Vehicle - Personal Injury,Vehicle Incident,62,Vehicle Collision,0,03,From Ambulance,415.0,...,Rexdale Blvd,2021-04-30 12:58:26,2021-04-30 13:06:57,9.0,2021-04-30 13:23:58,17.0,0.0,43.7173,-79.5958,4
5,6,F21084623,WDH - Wires Down - Hydro,Other Emergency Events,50,"Power Lines Down, Arcing",0,04,From Police Services,445.0,...,Puckeridge Cres,2021-08-19 12:08:03,2021-08-19 12:15:08,7.0,2021-08-19 12:18:20,3.0,0.0,43.6643,-79.5631,8

In [25]:
df_finally3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 53166 entries, 1 to 134537
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   _id                          53166 non-null  int32
 1   INCIDENT_NUMBER              53166 non-null  object
 2   Initial_CAD_Event_Type       53166 non-null  object
 3   Initial_CAD_Event_Call_Type  53166 non-null  object
 4   Final_Incident_ID            53166 non-null  object
 5   Final_Incident_Types         53166 non-null  object
 6   Event_Alarm_Level            53166 non-null  int64
 7   Call_ID                      53166 non-null  object
 8   Call_Origin                  53166 non-null  object
 9   Incident_Station_Area        53166 non-null  float64
 10  Incident_Ward                53166 non-null  int64
 11  Location                     53166 non-null  object
 12  TFS_Alarm_Time               53166 non-null  datetime64[ns]
 13  TFS_Arrival_Time             53166 non-null  datetime64[ns]
 14  Time_Taken_to_Arrive         53166 non-null  float64
 15  Last_TFS_Unit_Clear_Time     53166 non-null  datetime64[ns]
 16  Total_Time_at_Scene          53166 non-null  float64
 17  Persons_Rescued              53166 non-null  float64
 18  Latitude                     53166 non-null  float64
 19  Longitude                    53166 non-null  float64
 20  Month                        53166 non-null  int32
dtypes: datetime64[ns](3), float64(6), int32(2), int64(2), object(8)
memory usage: 8.5+ MB

In [52]:
# save new data frame as a csv file
df_finally3.to_csv("dataset.csv", encoding='utf8', index=False)